=== gitter-badger/Activity-Manager/misc/doc/books/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book (id, title, chapter*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT chapter (id?, title?, body)>
<!-- id : déjà défini pour le noeud book -->
<!-- ELEMENT id (#PCDATA) -->
<!-- title : déjà défini pour le noeud book -->
<!-- ELEMENT title (#PCDATA) -->

<!ELEMENT body (p*)>

<!ELEMENT p (#PCDATA|bold|italic|underlined|center|code|ul|ol|img|a|br)*>
<!ELEMENT code (#PCDATA|bold|italic|underlined)*>
<!ELEMENT br EMPTY>

<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA|p|bold|italic|underlined|code|ul|ol|img|a|center)*>

<!ELEMENT ol (li+)>
<!-- li : déjà défini pour le noeud ul -->
<!-- ELEMENT li (#PCDATA) -->

<!ELEMENT img EMPTY>
<!ATTLIST img thumbnail CDATA #IMPLIED>
<!ATTLIST img src CDATA #REQUIRED>

<!ELEMENT center (#PCDATA|bold|italic|underlined|code|img|a|br)*>
<!ELEMENT bold (#PCDATA|italic|underlined)*>
<!ELEMENT italic (#PCDATA|bold|underlined)*>
<!ELEMENT underlined (#PCDATA|bold|italic)*>

<!ELEMENT a (#PCDATA|bold|italic|underlined|center|code|img)*>
<!ATTLIST a href CDATA #REQUIRED>
<!ATTLIST a target CDATA #IMPLIED>
<!ATTLIST a type (book-ref|local-ref|external-ref) "external-ref">

=== gitter-badger/Activity-Manager/misc/doc/books/overview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
	<id>overview</id>
	<title>Overview</title>

	<chapter>
		<body>
			<p>Activity Manager is a project management tool. It helps a project
				leader to manage and check his collaborators activity. Simple to use,
				lightweight, but very efficient and customizable !</p>
			<p>Activity Manager is open source software. You can use it
				and redistribute it freely (see <a href="legal" type="book-ref">legal</a>
				for more details).</p>
			<p>The tool's features are :
				<ul>
					<li>Durations repository administration</li>
					<li>Collaborators repository administration</li>
					<li>Tasks repository administration</li>
					<li>Contributions management (=activity management)</li>
					<li>Extensible report facility (with built in templates)</li>
					<li>XML database export/import</li>
					<li>EXCEL export</li>
				</ul>
			</p>
			<p>The application allows to build and maintain a hierarchical task
				tree. It works with a very simple database model that allows
				to build quicly custom reports through the report facility or
				through simple SQL requests. Activity Manager is customizable.</p>
			<p>Coded in Java, Activity Manager can be used in three different modes :
				<ul>
					<li>Standalone mode (with an embeded HSQL database)</li>
					<li>MySQL Server mode</li>
					<li>Custom mode (user defined database for skilled users)</li>
				</ul>
				Custom mode may require advanced java notions, like CLASSPATH
				manipulation, particulary if you wish to use a database which is
				different from MySql and HSQL.
			</p>
			<p>It has been tested on Windows XP and Mandrake Linux 9.1 (GTK) and
				may work with any version of MySQL.
				<center>
					<img thumbnail="tasks-tab-small.png" src="tasks-tab.png"/>
				</center>
			</p>
		</body>
	</chapter>

</book>

=== gitter-badger/Activity-Manager/misc/doc/books/screenshots.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
	<id>screenshots</id>
	<title>Screenshots</title>

	<chapter>
		<body>
			<p>
				<center>
					Database connection tab<br/>
					<img thumbnail="database-tab-small.png" src="database-tab.png"/>
				</center>
				<br/>
			</p>
			<p>
				<center>
					Taks management tab<br/>
					<img thumbnail="tasks-tab-small.png" src="tasks-tab.png"/>
				</center>
				<br/>
			</p>
			<p>
				<center>
					Contributions management tab<br/>
					<img thumbnail="contributions-tab-small.png" src="contributions-tab.png"/>
				</center>
				<br/>
			</p>
			<p>
				<center>
					Collaborators management tab<br/>
					<img thumbnail="collaborators-tab-small.png" src="collaborators-tab.png"/>
				</center>
				<br/>
			</p>
		</body>
	</chapter>

</book>

=== gitter-badger/Activity-Manager/misc/doc/books/legal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
	<id>legal</id>
	<title>Legal</title>

	<chapter>
		<body>
			<p>Activity Manager is licensed under a BSD License,<br/>
				see <a target="newWin" href="LICENSE.txt" type="local-ref">LICENSE.txt</a> for details.
			</p>
			<p>Activity Manager includes software developed by<br/>
				The Apache Software Foundation (<a target="newWin" href="http://www.apache.org/">http://www.apache.org/</a>).
			</p>
			<p>This product also includes software developped by :
				<ul>
					<li>The Eclipse foundation (<a target="newWin" href="http://www.eclipse.org">http://www.eclipse.org</a>)</li>
					<li>MySQL organization (<a target="newWin" href="http://www.mysql.com">http://www.mysql.com</a>)</li>
					<li>The HSQLDB Development Group (<a target="newWin" href="http://www.hsqldb.org">http://www.hsqldb.org</a>)</li>
				</ul>
			</p>
		</body>
	</chapter>

</book>

=== gitter-badger/Activity-Manager/misc/doc/books/installation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
	<id>installation</id>
	<title>Installation</title>

	<chapter>
		<id>prerequesites</id>
		<title>Pre-requesites</title>
		<body>
			<p>Activity Manager needs a Java Development Kit (see 
				<a target="newWin" href="http://java.sun.com">http://java.sun.com</a>).
				The JDK must be rightly configured (ie. in the PATH environment
				variable).</p>
			<p>Optionnaly, if you don't want to work in standalone mode
				(refer to the <a href="userGuide#dbinit" type="book-ref">user guide</a>
				for more details about the different modes), you will need a MySQL
				database server.
				In that case, we suppose that it is rightly configured and that
				you have the root password.	MySQL Administrator and MySQL Query Browser
				may help you to configure your server.
			</p>
			<p>Activity Manager has been tested with JDK1.4.2 and MySQL Server 4.1.14 on
				a windows platform (Win2000 &amp; WinXP).</p>
		</body>
	</chapter>

	<chapter>
		<id>binaries</id>
		<title>Binaries installation</title>
		<body>
			<p>Download the <a href="https://sourceforge.net/projects/activitymanager/files/" type="external-ref">binary</a>
			archive and simply uncompress it on your disk wherever you want to.</p>
		</body>
	</chapter>

	<chapter>
		<id>dbinit</id>
		<title>Database initialization</title>
		<body>
			<p>Now, Activity Manager creates automatically the database tables.
				For this reason, this step is really light weight.</p>
			<p>
				<ol>
					<li>
						<p><underlined>Standalone mode :</underlined> nothing to do !</p>
					</li>
					<li><underlined>MySQL server mode :</underlined> (database and user creation)
						<p>Check that the parameter 'skip-networking' is commented
						in mysql configuration file, especially on linux platforms
						(typically located in <code>c:\windows\my.cnf</code>,
						<code>c:\windows\my.ini</code>, <code>/etc/my.cnf</code>,
						<code>/etc/my.ini</code>, ... (this parameter is not
						compatible with JDBC access))</p>
						
						<p>If you want to work with a different account than 
						<code>root</code> (which is a good idea!), follow these steps :</p>
						<p>Connect to MySQL database server with your root account :<br/>
						<code>mysql -u root -p [-h <italic>&lt;mysql host&gt;</italic>] mysql</code>
						</p>
						<p>Create the database by executing the following queries (choose a name for
						your database) :<br/>
						<code>drop database if exists <italic>&lt;your database name&gt;</italic>;</code><br/>
						<code>create database <italic>&lt;your database name&gt;</italic>;</code>
						</p>
						<p>Create a user account by executing the following queries (choose
						a name and a password for your database user) :<br/>
						<code>delete from mysql.user where user='<italic>&lt;your user name&gt;</italic>';</code><br/>
						<code>grant all privileges on <italic>&lt;your database name&gt;</italic>.* to <italic>&lt;your user name&gt;</italic>@'%'
						identified by '<italic>&lt;your password&gt;</italic>';</code><br/>
						<code>flush privileges;</code>
						</p>
						<p>Disconnect from the database with the command :
						<code>quit</code></p>
					</li>
					<li><underlined>Custom mode :</underlined> help yourself ! (contact me if you need a help)</li>
				</ol>
			</p>
		</body>
	</chapter>

	<chapter>
		<id>datamigration</id>
		<title>Data migration from version 0.2 to version 0.3</title>
		<body>
			<p>
				In order to migrate a V0.2 model to a V0.3 compliant model, follow
				these steps :
				<ul>
					<li>With Activity Manager V0.2, export the model (in the database
					tab, specify a file name and click on export)</li>
					<li>Make a backup of the file you've just generated</li>
					<li>Edit the XML file with a text editor (TextPad or anything else)</li>
					<li>Localize the duration nodes which may look like this : 
						<code>&lt;duration&gt;25&lt;duration&gt;</code></li>
					<li>Modify each duration node like this : 
						<code>&lt;duration&gt;&lt;value&gt;25&lt;/value&gt;&lt;/duration&gt;</code></li>
					<li>Save the file.</li>
					<li>If you use MySql, prepare a database for Activity Manager 0.3 
						(see '<a href="#dbinit" type="book-ref">Database initialization</a>'
						for more details)</li>
					<li>Start Activity Manager V0.3 and import this file (in the database
						tab, specify the file name, click on import and click successively on 
						'OK', 'Yes', 'Yes', 'Yes', 'Yes', 'No')</li>
					<li>It should be over!</li>
				</ul>
			</p>
		</body>
	</chapter>

	<chapter>
		<id>startup</id>
		<title>Start the application</title>
		<body>
			<p>Please refer to the <a href="userGuide#startup" type="book-ref">User Guide</a>
				for more details about how to run Activity Manager.
				<center>
					<img thumbnail="database-tab-small.png" src="database-tab.png"/>
				</center>
			</p>
		</body>
	</chapter>

</book>

=== gitter-badger/Activity-Manager/misc/doc/books/releaseNotes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">
<book>
	<id>releaseNotes</id>
	<title>Release notes</title>

	<chapter>
		<body>
			<p>
				<ul>
					<li>
						<bold>Activity Manager V0.3 :</bold>
						<ul>
							<li>
								Added a task search feature<br/>
								<img src="release-notes/0.3/task-search.png"/><br/>
							</li>
							<li>
								Added a task selection history in the task chooser popup<br/>
								<img src="release-notes/0.3/tasks-history.png"/><br/>
							</li>
							<li>
								Added a column sort feature on the collaborators tab<br/>
								<img src="release-notes/0.3/collaborators-sort-feature.png"/><br/>
							</li>
							<li>
								Added a activation feature on the duration and collaborators tabs<br/>
								<img src="release-notes/0.3/collaborators-activation-feature.png"/><br/>
							</li>
							<li>
								Added a contribution sum for each day<br/>
								<img src="release-notes/0.3/contributions-day-sum.png"/><br/>
							</li>
							<li>Added automatic refresh on the contribution tab when :
								<ul>
									<li>a duration is modified, added or removed</li>
									<li>a collaborator is modified, added or removed</li>
									<li>a task is modified, added or removed</li>
								</ul>
								<br/>
							</li>
							<li>
								Added a copy/paste feature between the tasks tab and
								the contributions tab
							</li>
							<li>Added a comment column in the tasks tree tab</li>
							<li>Added tasks code paths in the contributions list popup</li>
							<li>Added a remove feature on the contributions tab</li>
							<li>Added automatic .xls extension for EXEL exports</li>
							<li>SWT/JFace graphic library upgrade (v3.1=&gt;v3.2)</li>
						</ul>
						<br/>
					</li>
					<li>
						<bold>Activity Manager V0.2.1 :</bold>
						<ul>
							<li>Added XSL based documentation builder (misc/doc)</li>
							<li>Fixed sample reports configuration bug (missing / ahead task path)</li>
						</ul>
						<br/>
					</li>
					<li>
						<bold>Activity Manager V0.2 :</bold>
						<ul>
							<li>Added linux compatibility</li>
							<li>Added standalone mode (with an embedded HSQLDB database)</li>
							<li>Added automatic database initialization (light weight installation steps)</li>
							<li>Added durations repository administration</li>
							<li>Added XML database export/import</li>
							<li>Added EXCEL export of SWT tables</li>
							<li>Added 'About' tab with general information</li>
							<li>Added next/previous month/year navigability in the contributions tab</li>
							<li>Added up and down accelerators to move tasks</li>
						</ul>
						<br/>
					</li>
					<li>
						<bold>Activity Manager V0.1 :</bold>
						<ul>
							<li>Collaborators repository administration</li>
							<li>Tasks repository administration</li>
							<li>Contributions management (=activity management)</li>
							<li>Extensible report facility (with built in templates)</li>
						</ul>
						<br/>
					</li>
				</ul>
			</p>
		</body>
	</chapter>

</book>
